blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'),
]

buriti/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('eventos.urls', namespace='eventos')),
    url(r'^', include('videos.urls', namespace='videos')),
    url(r'^', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventos/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^eventos/$', views.index, name='index'),
]

videos/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^videos/$', views.index, name='index'),
]

blog/models.py
from django.db import models
from django.core.urlresolvers import reverse

class PostManager(models.Manager):

	def search(self, query):
		return self.get_queryset().filter(
			models.Q(titulo__icontains=query) | \
			models.Q(texto__icontains=query)
	)

class Post(models.Model):

	title = models.CharField('Titulo', max_length=100, blank=False)
	slug = models.SlugField('Slug')
	text = models.TextField('Texto', blank=False)
	date_post = models.DateField('Postado em', null=True, blank=False)
	image = models.ImageField(upload_to='blog/images', verbose_name='Imagem', null=True, blank=False)
	created_at = models.DateTimeField('Criado em', auto_now=False, auto_now_add=True, blank=False)
	updated_at = models.DateTimeField('Atualizado em', auto_now=True, auto_now_add=False)

	objects = PostManager()

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:details', kwargs={'slug': self.slug})

class Meta:
	ordering = ['-created_at']

eventos/models.py
from django.db import models

class EventoManager(models.Manager):

	def search(self, query):
		return self.get_queryset().filter(
			models.Q(title__icontains=query) | \
			models.Q(text__icontains=query)
	)

class Evento(models.Model):

	title = models.CharField('Titulo', max_length=100, blank=False)
	slug = models.SlugField('Slug')
	text = models.TextField('Descrição', blank=False)
	date_evento = models.DateField('Data do evento', null=True, blank=False)
	created_at = models.DateTimeField('Criado em', auto_now=False, auto_now_add=True, blank=False)
	updated_at = models.DateTimeField('Atualizado em', auto_now=True, auto_now_add=False)

	objects = EventoManager()

	def __str__(self):
		return self.title

class Meta:
	ordering = ['-created_at']
			

videos/models.py
from django.db import models

class VideoManager(models.Manager):

	def search(self, query):
		return self.get_queryset().filter(
			models.Q(title__icontains=query) | \
			models.Q(link__icontains=query) | \
			models.Q(text__icontains=query)
	)

class Video(models.Model):

	title = models.CharField('Titulo', max_length=100, blank=True)
	link = models.CharField('Link', max_length=100, blank=False)
	slug = models.SlugField('Slug')
	text = models.TextField('Descrição', blank=False)
	date_post = models.DateField('Postado em', null=True, blank=False)
	created_at = models.DateTimeField('Criado em', auto_now=False, auto_now_add=True, blank=False)
	updated_at = models.DateTimeField('Atualizado em', auto_now=True, auto_now_add=False)

	objects = VideoManager()

	def __str__(self):
		return self.title

class Meta:
	ordering = ['-created_at']

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .models import Post

def index(request):
	posts = Post.objects.all()
	paginator = Paginator(posts, 3)

	
	if request.GET.get('q'):
		posts = posts.filter(
			Q(title__icontains=posts) | \
			Q(text__icontains=posts)			
			).distinct()

	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
	# If page is not an integer, deliver first pageuery.
		posts = paginator.page(1)
	except EmptyPage:
	# If page is out of range (e.g. 9999), deliver last page of results.
		posts = paginator.page(paginator.num_pages)
	
	template_name = 'blog/index.html'
	context = {
		'posts': posts
	}
	return render(request, template_name, context)


def details(request, slug):	
	post = get_object_or_404(Post, slug=slug)
	context = {
		'post': post
	}
	template_name = 'blog/details.html'
	return render(request, template_name, context)

eventos/views.py
from django.shortcuts import render
from .models import Evento

def index(request):
	eventos = Evento.objects.all()
	template_name = 'eventos/index.html'
	context = {
		'eventos': eventos
	}
	return render(request, template_name, context)

videos/views.py
from django.shortcuts import render
from .models import Video

def index(request):
	videos = Video.objects.all()
	template_name = 'videos/index.html'
	context = {
		'videos': videos
	}
	return render(request, template_name, context)

blog/templates/blog/details.html
{% extends 'base.html' %}

{% block content %}
    <!-- INICIO SESSAO CONTEUDO -->
    <section class="container">
      
      <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title -->
                <h1>{{ post }}</h1>

                <!-- Author 
                <p class="lead">
                    by <a href="#">{{ post.author }}</a>
                </p>-->

                <hr>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span>Postado em {{ post.date_post }}</p>

                <hr>

                <!-- Preview Image 
                <img class="img-responsive" src="#" alt="">-->

                <!-- Post Content -->
                {{ post.text | linebreaks }}

            </div>

            <!-- Blog Sidebar Widgets Column -->
          <div class="col-md-4">

              <!-- Blog Search Well -->
              <div class="well">
                  <h4>Blog Search</h4>
                  <div class="input-group">
                      <input type="text" class="form-control">
                      <span class="input-group-btn">
                          <button class="btn btn-default" type="button">
                              <span class="glyphicon glyphicon-search"></span>
                      </button>
                      </span>
                  </div>
                  <!-- /.input-group -->
              </div>
              
              <!-- Blog Categories Well -->
              <div class="well">
                  <h4>Congregações</h4>
                  <div class="row">
                      <div class="col-lg-6">
                          <ul class="list-unstyled">
                              <li><a href="#">Betel</a>
                              </li>
                              <li><a href="#">Nova Jerusalém</a>
                              </li>
                              <li><a href="#">Nova Sião</a>
                              </li>
                              <li><a href="#">Vale de Benção</a>
                              </li>
                          </ul>
                      </div>
                      
                  </div>
                  <!-- /.row -->
              </div>

              <!-- Side Widget Well -->
                <div class="well">
                    <h4>Reflexão</h4>
                    <p>"Aquele que encontra uma esposa, acha o bem, e alcança a benevolência do Senhor."
                    (Provérbios 18:22)</p>
                </div>

          </div>
      
    </section><!-- FIM SESSAO CONTEUDO -->

{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block content %}

    <!-- INICIO SESSAO CONTEUDO -->
    <section class="container">

          <!-- Blog Entries Column -->
          <div class="col-md-8">

              <div class="row">

                {% for post in posts %}
                <div class="col-xs-12 col-sm-6">
                    <!-- First Blog Post -->
                    <figure class="thumbnail">
                        <a href="{{ post.get_absolute_url }}">
                          <img class="img-responsive" src="{{ post.image.url }}">
                          <figcaption class="caption">
                            <h3>{{ post.title }}</h3>
                            <p><span class="glyphicon glyphicon-time"></span>Postado em {{ post.date_post }}</p>
                          </figcaption>
                        </a>
                    </figure>
                </div>

                {% empty %}
                <div class="col-xs-12 col-sm-12">
                    <h2>Em breve teremos conteúdo!</h2>
                    <hr>
                </div>
                {% endfor %}
              </div>

              <ul class="pager">
                  {% if posts.has_previous %}
                  <li class="previous">
                      <a href="?page={{ posts.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&larr; Voltar</a>
                  </li>
                  {% else %}
                  <li class="previous disabled">
                      <a href="#">&larr; Voltar</a>
                  </li>
                  {% endif %}

                  <span class="current">
                    Página {{ posts.number }} de {{ posts.paginator.num_pages }}.
                  </span>

                  {% if posts.has_next %}
                  <li class="next">
                      <a href="?page={{ posts.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Avançar &rarr;</a>
                  </li>
                  {% else %}
                  <li class="next disabled">
                      <a href="#">Avançar &rarr;</a>
                  </li>
                  {% endif %}
              </ul>

          </div>

          <!-- Blog Sidebar Widgets Column -->
          <div class="col-md-4">

              <!-- Blog Search Well -->
              <div class="well">
                  <h4>Faça uma busca no site</h4>
                    <form method="GET" action="">
                      <div class="input-group">
                        <input class="form-control" type="text" placeholder="Pesquisar" name="q" value="{{ request.GET.q }}">
                        <span class="input-group-btn">
                          <button class="btn btn-default" type="submit" value="Search">
                              <span class="glyphicon glyphicon-search"></span>
                          </button>
                        </span>
                      </div>
                    </form>
                  <!-- /.input-group -->
              </div>
              
              <!-- Blog Categories Well -->
              <div class="well">
                  <h4>Congregações</h4>
                  <div class="row">
                      <div class="col-lg-6">
                          <ul class="list-unstyled">
                              <li><a href="#">Betel</a>
                              </li>
                              <li><a href="#">Nova Jerusalém</a>
                              </li>
                              <li><a href="#">Nova Sião</a>
                              </li>
                              <li><a href="#">Vale de Benção</a>
                              </li>
                          </ul>
                      </div>
                      
                  </div>
                  <!-- /.row -->
              </div>

              <!-- Side Widget Well -->
                <div class="well">
                    <h4>Reflexão</h4>
                    <p>"Aquele que encontra uma esposa, acha o bem, e alcança a benevolência do Senhor."
                    (Provérbios 18:22)</p>
                </div>

          </div>

    </section><!-- FIM SESSAO CONTEUDO -->

{% endblock %}

eventos/templates/eventos/index.html
{% extends 'base.html' %}

{% block content %}
    <!-- INICIO SESSAO CONTEUDO -->
    <section class="container">

    <!-- Blog Entries Column -->
          <div class="col-md-8">

              <div class="row">

                <div class="col-lg-12">
                    <h1><span class="glyphicon glyphicon-calendar"></span>&nbsp Agenda de eventos para 2017</h1>
                    <hr>
                </div>
                {% for evento in eventos %}
                  <div class="col-lg-12">

                    <div>
                      <h2><span class="glyphicon glyphicon-pushpin"></span>&nbsp {{ evento.title }}</h2>
                      <p class="lead">
                        {{ evento.text | linebreaks }}
                      </p>
                      <p>Data de realizacão:&nbsp{{ evento.date_evento }}</p>
                      <hr>
                    </div>
                  </div>
                  {% empty %}
                    <div class="col-xs-12 col-sm-12">
                        <h2>Em breve teremos conteudo nessa sessão!</h2>
                        <hr>
                    </div>
                {% endfor %}

                </div>
              </div>
          </div>
    
        <!-- Blog Sidebar Widgets Column -->
          <div class="col-md-4">

              <!-- Blog Search Well -->
              <div class="well">
                  <h4>Blog Search</h4>
                  <div class="input-group">
                      <input type="text" class="form-control">
                      <span class="input-group-btn">
                          <button class="btn btn-default" type="button">
                              <span class="glyphicon glyphicon-search"></span>
                      </button>
                      </span>
                  </div>
                  <!-- /.input-group -->
              </div>
              
              <!-- Blog Categories Well -->
              <div class="well">
                  <h4>Congregações</h4>
                  <div class="row">
                      <div class="col-lg-6">
                          <ul class="list-unstyled">
                              <li><a href="#">Betel</a>
                              </li>
                              <li><a href="#">Nova Jerusalém</a>
                              </li>
                              <li><a href="#">Nova Sião</a>
                              </li>
                              <li><a href="#">Vale de Benção</a>
                              </li>
                          </ul>
                      </div>
                      
                  </div>
                  <!-- /.row -->
              </div>

              <!-- Side Widget Well -->
              <div class="well">
                  <h4>Reflexão</h4>
                  <p>"Aquele que encontra uma esposa, acha o bem, e alcança a benevolência do Senhor."
                  (Provérbios 18:22)</p>
              </div>

          </div>
      
    </section><!-- FIM SESSAO CONTEUDO -->
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href='{% static "_bootstrap/css/bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "_css/style.css" %}'>
    <!--<link rel="stylesheet" href='{% static "_css/blueberry.css" %}'> -->
    <!-- As 3 meta tags acima *devem* vir em primeiro lugar dentro do `head`; qualquer outro conteúdo deve vir *após* essas tags -->

    <title>CIADSETA Buriti</title>

    <!-- Bootstrap -->
    <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet">

    <!-- HTML5 shim e Respond.js para suporte no IE8 de elementos HTML5 e media queries -->
    <!-- ALERTA: Respond.js não funciona se você visualizar uma página file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>
    <!-- INICIO MENU -->
    <header>
      <nav id="top-navbar" class="navbar navbar-default navbar-fixed-top"> 
        <div class="navbar-header">
          <button type="button" id="bt-menu" class="navbar-toggle collapsed" data-toggle="collapse" role="button" data-target="#collapse-navbar" aria-expanded="false">
              <div id="icon-menu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </div>
            </button>
            <a class="navbar-brand" id="logo-img" href="{% url 'blog:index' %}">
              <img src='{% static "_img/logo.png" %}'>
            </a>
            <a id="logo-text" class="navbar-brand" href="{% url 'blog:index' %}">CIADSETA Buriti</a>
        </div>
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="collapse-navbar">
            <ul class="nav navbar-nav" id="itens-menu">
              <li><a href="{% url 'blog:index' %}">Início</a></li>
              <li><a href="{% url 'videos:index' %}">Vídeos</a></li>
              <li><a href="{% url 'eventos:index' %}">Eventos</a></li>
              <li><a href="#contato">Contato</a></li>
            </ul>           
          </div>
        </div>

      </nav>
     
    </header><!-- FIM MENU -->

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="4800">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src='{% static "_img/depo1.png" %}' alt="...">
        </div>

        <div class="item">
          <img src='{% static "_img/depo2.png" %}' alt="...">
        </div>

        <div class="item">
          <img src='{% static "_img/depo3.png" %}' alt="...">
        </div>

      </div>
    </div>

    <!-- INICIO SESSAO CONTEUDO -->
    
    {% block content %}{% endblock %}

    <!-- FIM SESSAO CONTEUDO -->

    <!-- INICIO FOOTER -->
    <footer class="simple-footer">
        <div class="container">
          <address id="contato">
            <strong>Assembleia de Deus - CIADSETA</strong><br>
            Rua Tancredo Neves, Nº 326, Centro<br>
            Buriti do Tocantins - TO<br>
            <abbr>Fone:&nbsp</abbr>(63) 8463-6815
          </address>

          <address>
            <strong>E-mail</strong><br>
            <a href="mailto:#">kcyo2012@gmail.com</a>
          </address>
          <p class="copyright text-center">&copy; CIADSETA Buriti - TO. Todos os direitos reservados.</p>
        </div>
    </footer><!-- FIM FOOTER -->

    <!-- jQuery (obrigatório para plugins JavaScript do Bootstrap) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <!-- Inclui todos os plugins compilados (abaixo), ou inclua arquivos separadados se necessário -->
    <script src='{% static "_bootstrap/js/bootstrap.min.js" %}'></script>
    <script src='{% static "_js/navbar-fix.js" type="text/javascript"  %}'></script>
    <!-- <script src='{% static "_js/blueberry.js" type="text/javascript"  %}'></script> -->
  </body>
</html>

videos/templates/videos/index.html
{% extends 'base.html' %}

{% block content %}
    <!-- INICIO SESSAO CONTEUDO -->
    <section class="container">
      
      <div class="row">
            <div class="container">
                <h1><span class="glyphicon glyphicon-facetime-video"></span>&nbsp Vídeos</h1>
                <hr>
            </div>
            <!-- Blog Post Content Column -->
            <div class="col-md-12">
                {% for video in videos %}
                <div class="col-xs-12 col-sm-4">
                    <div class="panel panel-default">
                        <div class="embed-responsive embed-responsive-16by9">
                              <iframe class="embed-responsive-item" src="{{ video.link }}" allowfullscreen></iframe>
                        </div>
                        <div class="panel-body">
                            {{ video.text }}
                        </div>
                    </div>
                </div>
                {% empty %}
                <div class="col-xs-12 col-sm-12">
                    <h2>Em breve teremos conteudo nessa sessão!</h2>
                    <hr>
                </div>
                {% endfor %}

            </div>

        </div>
        <!-- /.row -->
      
    </section><!-- FIM SESSAO CONTEUDO -->
{% endblock %}